/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jacoco_nfd_NativeFileDialog */

#ifndef _Included_com_jacoco_nfd_NativeFileDialog
#define _Included_com_jacoco_nfd_NativeFileDialog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jacoco_nfd_NativeFileDialog
 * Method:    getFileNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jacoco_nfd_NativeFileDialog_getFileNative
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_jacoco_nfd_NativeFileDialog
 * Method:    getMultipleFilesNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jacoco_nfd_NativeFileDialog_getMultipleFilesNative
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_jacoco_nfd_NativeFileDialog
 * Method:    getPathNative
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jacoco_nfd_NativeFileDialog_getPathNative
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jacoco_nfd_NativeFileDialog
 * Method:    saveFileNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jacoco_nfd_NativeFileDialog_saveFileNative
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
